# Licensed under the Apache-2.0 license.

[package]
name = "systemrdl"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.100"
same-file = "1.0.6"
winnow = "0.7.14"
